### ISSUE TITLE
PMTable issue

### ISSUE THREAD

**Issue by itsmekarthikeyan** [qwasli/PMTable#1]
Hi,

I am using PMTable 1.6. In this version the tooltip in table cell is not getting displayed. Please let me know
is it possible to display a tooltip for table cells or not. If your answer is yes, how to do that?

Further, I am using vaadin 7.5.8 version.

Thanks

Karthikeyan

**Comment by qwasli** [comment]
Hi, 

Sorry for answering this late, I missed the notification of this report.
I just tested to display the tooltip with the newest version and 1.6 (+ vaadin 7.5.8) using ItemDescriptionGenerator. And it seems to work. How did you try do do it?
Why are you using such an old version?

Cheers,
Raffael

**Comment by itsmekarthikeyan** [comment]
Closing the issue.
